# Generated by Django 5.2.3 on 2025-06-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_role'),
        ('course', '0004_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Follow',
        ),
    ]
