# Generated by Django 5.2.3 on 2025-06-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_user_alter_lesson_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='true',
            field=models.BooleanField(default=True),
        ),
    ]
