# Generated by Django 5.2.3 on 2025-06-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_test_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
