# Generated by Django 5.2.3 on 2025-06-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_role'),
        ('course', '0008_test_end_date_test_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBasicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_basic_test', to='course.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_basic_user', to='blog.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
