# Generated by Django 5.2.3 on 2025-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_testbasicmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='true',
        ),
        migrations.AddField(
            model_name='testbasicmodel',
            name='true',
            field=models.BooleanField(default=True),
        ),
    ]
