# Generated by Django 5.2.3 on 2025-06-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_rename_true_testbasicmodel_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbasicmodel',
            old_name='submitted',
            new_name='started_at',
        ),
    ]
