# Generated by Django 5.2.3 on 2025-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Teacher'), (2, 'Student'), (3, 'Admin')], default=2),
        ),
    ]
